name: bb_example_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  api:
    path: ../../resources/api
  awesome_dialog: ^3.2.0
  common:
    path: ../../resources/common
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  neon_widgets: ^2.0.0
  crypto_dart: ^1.0.3+2
  encrypt: ^5.0.3
  tuple: ^2.0.2
  flutter_nfc_kit: ^3.4.2
  webview_flutter: ^4.5.0
  web3dart: ^2.7.3
  pretty_animated_buttons: ^0.0.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  go_router: ^13.0.1
  share_plus: ^7.2.2
  http: ^1.2.0
  logger: ^2.0.2+1
  nfc_manager: ^3.4.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  universal_io: ^2.2.2
  values:
    path: ../../resources/values
  widgets:
    path: ../../resources/widgets
  

dev_dependencies:
  device_preview: ^1.1.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  # assets:
  #   - packages/values/assets/images/
  #   - packages/values/assets/icons/

  

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
