name: bb_example_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  api:
    path: ../../resources/api
  common:
    path: ../../resources/common
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  go_router: ^13.0.1
  logger: ^2.0.2+1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  universal_io: ^2.2.2
  values:
    path: ../../resources/values
  widgets:
    path: ../../resources/widgets
  

dev_dependencies:
  device_preview: ^1.1.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  # assets:
  #   - packages/values/assets/images/
  #   - packages/values/assets/icons/

  

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
